ultimatum:
	gcc -o ultimatumserver -Wall -g -pthread server.c
	gcc -o ultimatumclient -Wall -g -pthread client.c
	gcc -o ultimatumserver32 -m32 -g -Wall -pthread server.c
	gcc -o ultimatumclient32 -m32 -g -Wall -pthread client.c
